name: Build and test with ghcr.io/kxcinc/ocaml-general
description: Build and test OCaml projects using the ghcr.io/kxcinc/ocaml-general docker container
author: KXC Members and Contributors
branding:
  icon: sunrise
  color: orange
inputs:

  build-command:
    description: "Override the default build command"
    required: false
    default: ""

  test-command:
    description: "Override the default test command"
    required: false
    default: ""
  skip-testing:
    description: "Whether or not to skip running the tests"
    required: false
    default: false

  setup-command:
    description: "Override the default setup command"
    required: false
    default: "opam install . --yes --deps-only --with-test --verbose"
  skip-setup:
    description: "Whether or not to skip running setups"
    required: false
    default: false

  with-odoc:
    description: "Build odoc documents"
    required: false
    default: false
  odoc-build-command:
    description: "Override the default odoc build command"
    required: false
    default: "opam exec -- dune build @doc"

outputs:
  odoc-site-path:
    description: "Path to odoc document site build result, if with-odoc is set to true"

runs:
  using: composite
  steps:
    - name: Build and test with OCaml
      uses: kxcdev/ocaml-general-gha-bare@78ec6ee277e0ee5c0185e8f083cf51cb65cae5e4
      with:
        build-command: "${{ inputs.build-command }}"
        test-command: "${{ inputs.test-command }}"
        skip-testing: "${{ inputs.skip-testing }}"
        setup-command: "${{ inputs.setup-command }}"
        skip-setup: "${{ inputs.skip-setup }}"
        with-odoc: "${{ inputs.with-odoc }}"
        odoc-build-command: "${{ inputs.odoc-build-command }}"
